# Site settings
title: Nnup's world
SEOTitle: Nnup
header-img: img/home-bg.jpg
email: <a href="iron-bat@foxmail.com">iron-bat@foxmail.com</a>
description: "愿意今生约定，他生再拥抱"
keyword: "pai, 唐唐, Nnup, TEST"
url: "http://nnup.fun"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
#github_repo: "https://github.com/Nnup-vid/Nnup-vid.github.io" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "4 AM <br> 只做与正义无关的事"
sidebar-avatar: /img/avatar_m.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
#RSS: false
# weibo_username:     123
#zhihu_username:     123
#github_username:    123
#facebook_username:  123
#jianshu_username:   123
#twitter_username:   123




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: Nnup

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 3e99b98dfe0131518162                            #生成的clientID
  clientSecret: 05933a21d61ea915f0b46e2114502e0824a6659a    #生成的clientSecret
  repo: Nnup-vid.github.io    #仓库名称
  owner: Nnup-vid    #github用户名
  admin: Nnup-vid
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 0143ab0d89af3e1a246497f0be151238

# Google Analytics
#ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
#ga_domain: nnup.fun               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
#friends: [
#    {
#        title: "WY",
#        href: "http://xxx.com"
#    },{
#        title: "简书·BY",
#        href: "http://www.jianshu.com/u/xxx"
#    },{
#        title: "Apple",
#        href: "https://apple.com"
#    },{
#        title: "Apple Developer",
#        href: "https://developer.apple.com/"
#    }
#]
